version: "3"
services:
  collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4318:4318
      - 8378:8378
    volumes:
      - ../../conf/otel-collector-config.yaml:/conf/otel-collector-config.yaml
