name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.1, 3.0.1, 2.7.3, 2.6.7]

    steps:
      - uses: actions/checkout@v2

      - name: Run Collector
        run: docker-compose up -d

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Apply RubyGems fixes
        run: gem update --system
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rake test

  test-e2e-rails-7-barebones:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1]
    steps:
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Apply RubyGems fixes
        run: gem update --system
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: bundle install
      - name: Reset docker-compose for safety
        run: docker-compose down
      - name: Bring up dependencies via detached docker-compose
        run: docker-compose -f docker-compose.rails-7-barebones.yml up --build
      - name: Show logs
        run: docker-compose logs rails_7_barebones
      - name: Smoke test
        run: curl rails_7_barebones:3000
      - name: Run tests
        run: bundle exec rake test_e2e
      - name: Bring dependencies down
        run: docker-compose -f docker-compose.rails-7-barebones.yml down
